FROM joeljoos/nginx-amplify

# Copy nginx stub_status config
COPY loadbalancing-server.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
# COPY loadbalancing-server.conf /etc/nginx/conf.d/loadbalancing-server.conf
